export enum statsActionTypes {
	FETCH_DATA_REFRESHED_TIME = 'FETCH_DATA_REFRESHED_TIME',
	FETCH_DATA_SUMMARY = 'FETCH_DATA_SUMMARY',
	FETCH_CHARTS_DATA = 'FETCH_CHARTS_DATA',
	FETCH_WALETS_AMOUNT_BY_APP = 'FETCH_WALETS_AMOUNT_BY_APP',
	FETCH_TRANSACTIONS_AMOUNT_BY_APP = 'FETCH_TRANSACTIONS_AMOUNT_BY_APP',
	FETCH_MONTHLY_ACTIVE_SPENDERS_AMOUNT_BY_APP = 'FETCH_MONTHLY_ACTIVE_SPENDERS_AMOUNT_BY_APP',
	FETCH_CHARTS_DATA_SUCCESS = 'FETCH_CHARTS_DATA_SUCCESS',
	FETCH_CHARTS_DATA_FAILURE = 'FETCH_CHARTS_DATA_FAILURE',
	FETCH_SUMMARY_DATA_SUCCESS = 'FETCH_SUMMARY_DATA_SUCCESS',
	FETCH_DATA_REFRESHED_TIME_SUCCESS = 'FETCH_DATA_REFRESHED_TIME_SUCCESS'
}
